In [12]:
import os
import sys
import numpy as np
from random import shuffle

In [2]:
sys.path.append("../../")

In [3]:
from Libs.SharedLibs import getFileList;

In [5]:
wav_src_dir = "../../datasets/CurrentUse/wav_files/positive/"

In [11]:
#shuffle test
arr = np.array([[0, 0, 0], [1, 1, 1], [2, 2, 2], [3, 3, 3], [4, 4, 4]])
# Display original array
print("Original array:\n",arr,"\n")
# Creating target labels
tar = np.array([0, 1, 2, 3, 4])
# Display target labels
print("Target labels:\n",tar,"\n")
# Shuffling array and target labels by same order
ind = [i for i in range(len(arr))]
shuffle(ind)
arr_new = arr[ind]
tar_new = tar[ind]
# Display result
print("Shuffled array and target label with same order:\n",arr_new,"\n\n",tar_new,"\n")

Original array:
 [[0 0 0]
 [1 1 1]
 [2 2 2]
 [3 3 3]
 [4 4 4]] 

Target labels:
 [0 1 2 3 4] 

Shuffled array and target label with same order:
 [[2 2 2]
 [1 1 1]
 [3 3 3]
 [4 4 4]
 [0 0 0]] 

 [2 1 3 4 0] 



In [ ]:
def create_wav_list(wav_src_path)->list:
    wav_list = [];
    return wav_list;

In [ ]:
fold_dirs = ["fold1","fold2","fold3","fold4","fold5"];
classes = ["alarm",""]
upper_level_dir = "../../datasets/CurrentUse/wav_files/"